/* ACT I: THE CANDLE (Prologue - Chapter 5). Second-person retelling that keeps the novel's own wording wherever it can.
   Paragraph starting "@key " is spoken by that character's voice. Everything else is read by the narrator (Audra). */
window.AS_ACTS = [
  { n: 1, name: 'The Candle', ch: 'Prologue–Chapter 5' }, { n: 2, name: 'The Seven Sisters', ch: 'Chapters 6–13' },
  { n: 3, name: 'Town Hall', ch: 'Chapters 14–16' }, { n: 4, name: 'Undercover', ch: 'Chapters 17–24' },
  { n: 5, name: 'The Reckoning', ch: 'Chapters 25–31' }, { n: 6, name: 'Aftermath', ch: 'Chapters 32–34' }
];
window.AS_CHARS = {
  ethan: { g: 'm', rank: 0, pitch: 0.9, rate: 0.98 }, benjamin: { g: 'm', rank: 1, pitch: 0.7, rate: 0.85 }, charles: { g: 'm', rank: 1, pitch: 0.85, rate: 0.96 },
  mayor: { g: 'm', rank: 2, pitch: 0.8, rate: 1.05 }, brendon: { g: 'm', rank: 3, pitch: 0.95, rate: 0.97 },
  katherine: { g: 'f', rank: 2, pitch: 1.05, rate: 0.98 }, ashley: { g: 'f', rank: 2, pitch: 0.85, rate: 0.88 }, mackenzie: { g: 'f', rank: 1, pitch: 0.95, rate: 0.93 },
  gwyn: { g: 'f', rank: 1, pitch: 0.72, rate: 0.8 }
};
window.AS_CLUES = {
  candle: ['The Dry Spell Reliever', 'A purple candle from the Daylight Candle Shop and a prayer card: May love’s embrace meet me at dawn’s face.'],
  burns: ['The Burns', 'Singed skin and fingernail scratches at the throat, as on the other victims and on Kendra.'],
  scent: ['A Visitor', 'Candle wax and perfume. Gwyneth may not have slept alone.'],
  ben: ['Never Missed a Day', 'Benjamin: Gwyn never missed work. Mr. Stuart sent her building super to check on her.'],
  katherine: ['The Sheriff’s Daughter', 'Katherine: Gwyn lived alone after leaving a cheater. Her late father, the sheriff, hated the specters.'],
  charles: ['In a Hurry', 'Charles: on her last day Gwyn rushed out as if she had somewhere important to go.'],
  history: ['Browser History', 'Gwyn visited the Daylight Candle Shop, ending on the Dry Spell Reliever.'],
  victims: ['Five Victims', 'Amanda Price, Jenifer Martin, Linda Parker, Regina Fowler, Gwyneth Miller. All look like Kendra.'],
  presence: ['A Presence', 'Mackenzie: not a specter, but the energy of someone living, used as a weapon.'],
  throat: ['The Throat Chakra', 'The throat governs truth and speech. Someone may be silencing the victims to keep a secret.'],
  abigail: ['Abigail Stevens', 'Gwyn’s birth mother was strangled in the hospital the day Gwyn was born. Never solved.'],
  cordero: ['A Familiar Signature', 'Deputy Jonathan Cordero signed Abigail’s witness statements. He never told you.'],
  shelleys: ['The Shelleys', 'The richest family in town. They paid for the new hospital, built where the old one stood.']
};

(function () {
  var f = function (k) { return function (s) { return !s.f[k]; }; };
  var did = function (k) { return function (s) { return !!s.f[k]; }; };
  var mark = function (k, c) { return function (s) { s.f[k] = 1; if (c) AS.clue(s, c); }; };
  var ust = function (who, n) { return function (s) { s.trust[who] += n; }; };

  window.AS_STORY = {
    prologue: { act: 1, ch: 'Prologue', pov: 'GWYN', title: 'Dry Spell Reliever', amb: ['crickets', 'wind'], sting: 'candle',
      text: 'Gwyneth Miller leaves the Daylight Candle Shop clutching her purchase to her chest as if it were a lifesaver, taking it back to the one-bedroom apartment where she has lived alone for the past year.\n\nAfter finding her boyfriend in her bed with another woman for the third time, she kicked him out and swore off dating in the face of her obvious attraction to pretty-boy losers and scum. As she often does, she reminds herself that her father would turn over in his grave if he could see her now. One of his final battles as the sheriff of Specter was to get rid of the specters that wanted to make his town their home. But old Southern specters brought old Southern money, and that was the one thing the town had limped by without since the mills and factories shut down.\n\nThe instructions are simple: light the candle, say the prayer, and blow it out. She is to lie down and fall asleep, and when she awakens, her dry spell will be over.\n\n*“May love’s embrace meet me at dawn’s face,”* she reads. She takes a deep breath and blows the candle out.\n\nSomething finds her in the dark. It is gentle, and it is patient. She forces the disapproving image of her father’s face from her mind, and at that moment she cannot think of a single rational argument against the inclusion of specters in their community.\n\nThen, near dawn, the air changes. It turns cool, dry, and a little too thick to breathe.\n\nA pair of electric hot hands wrap around her neck. Her eyes open wide. She grasps her throat to peel the choking hands away but feels nothing there. The hands of the intruding presence go through her flesh and directly to her windpipe.\n\nShe squeezes out one final gurgle. The presence fades away as quickly as it came.',
      choices: [{ label: 'Monday', to: 'crime' }] },

    crime: { act: 1, ch: '1', pov: 'AUDRA', title: 'Half Past Noon', amb: ['hum', 'cicada'],
      enter: function (s) { s.shield = true; },
      text: function (s) {
        var t = 'It is half past noon on Monday when you step into the apartment of Gwyneth Miller. You were in Savannah the prior week but, as a native New Yorker, you are sure you will never get used to the stifling Georgia heat. The air conditioner is not on. You can hear the muffled sounds of country cops inevitably messing up the bedroom, which is now an official FBI crime scene.\n\nGwyneth Miller is the fifth victim of a suspected serial killer of the specter variety, who has a thing for dark-haired, dark-eyed women sleeping alone. You activate the specter shield you wear around your left wrist to block any specters from getting within five feet of you.\n\nYou have spent nearly four years on special assignments with the FBI investigating specter crimes. The biggest problem with catching a criminal specter is that they never leave any physical evidence: no DNA, no fingerprints, no calling card, no expository note, and no obvious motive.';
        if (s.f.room) t += '\n\nYou walk into the bedroom and immediately note the scent of candles and perfume. You suspect that maybe this woman did have a visitor the night before, and that this would not fit the profile of your four previous cases. You scan the room and make note of the cheap, feminine décor.';
        if (s.f.body) t += '\n\nGwyneth is lying in bed, on her side, with her hands near her throat, which is singed with strange burn marks. Her fingernails have scratched at her throat as well, peeling away some of the skin. These are the telltale signs of the specter you are following, but most disturbingly, this victim, like all the others, looks a lot like your sister.\n\n“Shit,” you say.';
        if (s.f.candle) t += '\n\nYou look over at the side table and take in the large purple candle. “What is this?” You lean in close. Next to it sits a tiny instruction card.\n\n*“May love’s embrace meet me at dawn’s face.”* The Daylight Candle Shop.';
        return t;
      },
      choices: [
        { label: 'Look at the purple candle by the bed', show: f('candle'), to: 'crime', fx: mark('candle', 'candle') },
        { label: 'Look at the body', show: f('body'), to: 'crime', fx: mark('body', 'burns') },
        { label: 'Look around the room', show: f('room'), to: 'crime', fx: mark('room', 'scent') },
        { label: 'That is enough. Someone is waiting for you.', to: 'ethan' }
      ] },

    ethan: { act: 1, ch: '1', pov: 'AUDRA', title: 'Hearing His Voice', amb: ['cicada'],
      text: function (s) {
        return (s.f.candle ? '@ethan “A candle from the Daylight Candle Shop.”\n\nHearing his voice, you take a shallow breath before quickly letting it out.' : 'Behind you, a voice you know. You take a shallow breath before quickly letting it out.') +
          '\n\nYou turn as he strolls through Gwyneth Miller’s bedroom door. He wears laid-back local Southern clothes, faded jeans with a slightly tattered T-shirt and baseball cap, but there is no mistaking the city attitude in his walk. Ethan Cole. When you received the initial fax of a possible fifth victim, you read his name on top of the report with disbelief.\n\nHis New York City swagger is enough to make a nun forget her vows just long enough to break them four or five times. He is six years older than you, but it looks good on him.\n\nYou say a prayer for Gwyneth and leave without another word to anyone. Ethan follows you out of the apartment building.\n\n@ethan “Hey, Audra. Wait up.”\n\n“I’m going to go over to the library and question the people she worked with.”\n\n@ethan “I already did that.”\n\n“Well, I’m going to do it as well,” you reply, making it clear that the investigation is now yours to control.\n\n@ethan “Okay, but listen. This town is full of – ”\n\n“Specters? Yeah, I know.” You roll your eyes at the thought of an entire town, in southern America of all places, home to people who have passed away.\n\n@ethan “Go easy with this case. Gwyneth was the past sheriff’s daughter. She was well liked and even loved for that. This town has come to peacefully co-exist with the specters. Don’t go shaking your FBI trained bias where it doesn’t belong.”';
      },
      choices: [
        { label: '“I don’t have time, Ethan.”', to: 'library', fx: ust('ethan', -1) },
        { label: '“Don’t worry, I won’t go around zapping your ghostly citizens.”', to: 'library', fx: ust('ethan', 1) },
        { label: '“You might want to warn the Daylight Candle Shop that they’re next on my list.”', to: 'library', fx: ust('specters', -1) }
      ] },

    library: { act: 1, ch: '1', pov: 'AUDRA', title: 'Mostly Students', amb: ['hum', 'murmur'],
      text: function (s) {
        var t = 'You drive the three blocks to the town’s public library. You find it hard to believe that people still go to the library, but when you walk in it is indeed full of people, mostly students. Most of them sit at computers playing games while listening to headphones.\n\nYou spot several specters dotting the library in various stages of manifestation. You can tell the newbies by their classic opaque ghost-like appearance. You never really mind those. In fact, you feel a great deal of sympathy for them, coming to terms with the fact that their lives are really over. It is the specters that have mastered every aspect of appearing normal, the ones that hide in plain sight pretending to be alive, that you don’t trust.';
        if (s.f.ben) t += '\n\nYou walk up to what appears to be an empty reference desk and are unsettled by the appearance of a specter who looks the part of a college kid with coke-bottle glasses and severe acne.' + (s.f.pushed ? '\n\n@benjamin “Whoa!”\n\nHe exclaims as your specter shield pushes him from his seat. @benjamin “What is that?” You deactivate the shield, knowing it would be impossible to get around with it on in a town full of ghosts.' : '') + '\n\n@benjamin “You here about Gwyn?” His voice is the usual hollow, otherworldly echo associated with specters still mastering speech without a voice box.\n\n@benjamin “She didn’t come into work this morning. Gwyn never missed a day. Mr. Stuart called Gwyn’s apartment when she didn’t show up but didn’t get an answer. Then he asked her super to check in on her. That’s when he found her.”\n\n“Who called the super?” you ask.\n\n@benjamin “Management.”\n\n“Thanks, uhm?”\n\n@benjamin “Benjamin. Benjamin Conner.”';
        if (s.f.kath) t += '\n\nYou catch sight of a woman in her late thirties, crying alone down an aisle. She quickly dries her red-rimmed blue eyes and crosses her arms over her chest.\n\n“Hi, I’m Agent Wheeler. I’m here about Gwyneth Miller. Did you know her?”\n\n@katherine “I’m Katherine Taylor. We worked here together for the last six years. She was such a nice girl. She’d never hurt a fly. I can’t believe anyone would...”\n\n“Do you know if Gwyneth was seeing anybody?”\n\n@katherine “No. She was seeing some loser about a year ago but kicked him out. She’s been alone ever since.”\n\n“Do you know if Gwyn was associating with any specters?”\n\n@katherine “No. Her father used to be the sheriff here. He made it clear that he didn’t like the specter invasion. Other than going to the college she was pretty loyal to his point of view.”';
        if (s.f.charles) t += '\n\nAt the manager’s door you hear hushed, muffled voices. You knock, and the voices stop. The door opens just wide enough for a tall, dark, and handsome man to peek his head out. His hair is disheveled, as if he has raked his hands through it several times. His eyes are bloodshot and there is a faint hint of liquor on his breath.\n\nA ghostly, feminine voice from inside says, “I’m outta here,” and a young girl with black and purple hair pushes past him and around you. Her shoulder vanishes and reappears as the rest of her clears you.\n\n@charles “My daughter, Amanda. I promised to do something remotely father-like and I had to back out because of the... situation. Charles Stuart. Come on in.”\n\n@charles “Gwyn? No, I don’t know anyone that didn’t like her. She was the quiet type. But very pleasant, great with the library patrons. Well, the last day she was here she seemed in an awful hurry to leave. Like she had somewhere important to go. I remember wondering if she’d met a new guy or something.”\n\nYou have to duck into an empty aisle as a flashback takes you over. You are fourteen again, in your older sister Kendra’s house. You hear a commotion that makes you get up from the television and walk toward her bedroom. “It’s okay,” you tell yourself in the present. “You’re not there anymore.” You take several breaths to steady yourself.';
        return t;
      },
      choices: [
        { label: 'Go to the reference desk', show: f('ben'), to: 'library', fx: function (s) { s.f.ben = 1; if (s.shield) { s.f.pushed = 1; s.shield = false; AS.syncShield(); } s.trust.specters += 1; AS.clue(s, 'ben'); } },
        { label: 'Go to the woman crying in the aisle', show: f('kath'), to: 'library', fx: mark('kath', 'katherine') },
        { label: 'Knock on the manager’s door', show: f('charles'), to: 'library', fx: mark('charles', 'charles') },
        { label: 'Check Gwyneth’s computer', to: 'computer' }
      ] },

    computer: { act: 1, ch: '1', pov: 'AUDRA', title: 'The Password Is Library', amb: ['hum', 'murmur'],
      text: '“The password is library,” Charles Stuart supplies. “I need to get back to my office.”\n\nYou sit at Gwyneth’s computer and power it up quickly. You go to the web browser and check the history. In the last four hours of her last day at work, Gwyneth Miller searched for and visited the Daylight Candle Shop’s website. The final page in her history is on the big purple candle called the Dry Spell Reliever.\n\nYou shake your head and take down the address. Then your stomach growls. You hopped an immediate flight out of Savannah not thirty minutes after waking up to the call of this latest murder. You need food and rest, and you decide you should find both, in that order.',
      enter: function (s) { AS.clue(s, 'history'); },
      choices: [{ label: 'Find something to eat', to: 'diner' }] },

    diner: { act: 1, ch: '2', pov: 'AUDRA', title: 'Barbecue and Ghosts', amb: ['murmur', 'hum'],
      text: 'As you drive through town, the unmistakable aroma of barbecue guides you to a hole in the wall with the moniker Bishop’s. You step into the diner/bar/café and feel the daggers of local, loyal patron stares. Walking past them in your Prada suit with silk shirt and red-soled Manolos, you realize you might have felt less conspicuous in a paper bag.\n\nA specter waitress, whom you are sure was a high school cheerleader, what with her winning smile and pumped-up attitude over barbecue, comes to take your order.\n\n@ashley “Hey, you here about Gwyn? Everyone knows everyone. Awful shame, she was so nice. Helped me every time I needed to find a book.”\n\nIt unnerves you how many young specters are in the small town. You want to think of them as old people who’ve had their time on Earth and needed to move on.\n\nYour boss, Assistant Director Jonathan Cordero, always seemed to have a soft spot for you, probably because he was the one who investigated your sister’s attempted murder when you were just fourteen. He is the one who came and found you just before your college graduation and recruited you into the FBI. You never thought much about why.\n\nThe flashback takes you over once more. You turn on your sister’s bedroom light to find her hanging in mid-air, clawing at the burned flesh around her throat. Suddenly, whatever held her up lets go and she falls back onto the bed.\n\nYou are pulled back by the sound of Bishop’s door opening. You sit up as you catch sight of Ethan. He searches the room and, when his eyes land on you, he smiles.\n\n@ashley “Hey, Sheriff! Can I get anything for you?”\n\n@ethan “I already ate. But thanks for the water and rolls.”\n\n“Sheriff?” you ask, unable to hide your bewildered confusion.\n\n@ethan “Long story.”',
      sting: 'cold',
      choices: [
        { label: '“I don’t believe in coincidences, Ethan. You should remember that much about me.”', to: 'station' },
        { label: '“You look okay.”', to: 'station', fx: ust('ethan', 1) },
        { label: 'Say nothing and eat your ribs.', to: 'station', fx: ust('ethan', -1) }
      ] },

    station: { act: 1, ch: '3', pov: 'AUDRA', title: 'A Type', amb: ['hum'],
      text: '@ethan “We’ll talk after lunch.” He lifts an eyebrow, and you realize he doesn’t want to talk amongst listening citizens.\n\nYou step into the four-room mobile home converted into a sheriff’s station and try not to let your disappointment show. There are two other desks in the room marked for a secretary and a deputy, but no one is there. An ancient filing cabinet takes up nearly half of the wall behind the sheriff’s desk.\n\nIn the back meeting room you open the briefcase and line up four separate files, in order from the first murder to the last.\n\n“Amanda Price of Boston, Massachusetts,” you say, and look at the girl’s postmortem mug shot. Her skin is grayish pale and her dark hair is pulled back off her lean face. The bruising from her own fingernail scratching, as well as the strange burn marks around her neck, stands out in the photograph like a gruesome necklace.\n\n“Jenifer Martin of Newark, New Jersey.” Then Linda Parker of Charlotte, North Carolina, and Regina Fowler of Savannah, Georgia.\n\n“All were alone and in bed at the time of their murders, most likely asleep.”\n\n@ethan “They all look alike.”\n\n“A serial killer with a type,” you agree. “A type that looks a lot like my sister.”\n\nEthan sits back as if a light bulb has gone off in his head.\n\n@ethan “Your sister was attacked like this, right? You think these are connected to your sister?”\n\n“I do,” you finally say aloud for the first time.',
      enter: function (s) { AS.clue(s, 'victims'); },
      choices: [
        { label: '“I ran to my sister’s room after hearing a crash.”', to: 'sister', fx: function (s) { s.f.told = 1; s.trust.ethan += 1; } },
        { label: 'Give him the facts and nothing else.', to: 'sister', fx: function (s) { s.f.told = 0; } }
      ] },

    sister: { act: 1, ch: '3', pov: 'AUDRA', title: 'Thirteen Years', amb: ['hum'],
      text: function (s) {
        var t = s.f.told
          ? '@ethan “Okay, tell me again about your sister’s case.” His face is set in an intense yet calm pose that says he is listening to your words, reading between the lines, and watching your body language.\n\n“I ran to my sister’s room after hearing a crash. She was up in the air grabbing for her throat. When I flipped on the light she fell back onto the bed. No one else was there. I called 9-1-1 and tried my best at CPR. She was almost nine months pregnant at the time.”\n\n@ethan “How is she now?”\n\n“She’s still in a coma. Nothing has changed in the past thirteen years.”\n\n@ethan “Oh, Rook.” It is the nickname he gave you your first day together as partners. @ethan “As far as you know there is no connection between your sister and this town?”\n\n“The only thing that has any meaning to me here is you,” you say, and you cannot hide the emotion in your eyes from him. “And once again, I have to say that I do not believe in coincidence.”\n\n@ethan “Me neither.”'
          : 'You give him the facts. Your sister was attacked the same way, thirteen years ago. You keep your voice level and your eyes on the files.\n\n@ethan “Okay.”\n\nHe lets you keep your distance. You notice that he noticed.';
        return t + '\n\nHe takes you back to the B&B. He doesn’t ask and he doesn’t wait for you to ask, just pulls you into a hungry kiss, and you feel yourself melt against him. The rest belongs to the two of you.\n\nBy a quarter past five Ethan sleeps as if dead to the world. You don’t want to wake him, and you don’t know if you would be able to cover up your raw feelings with the same nonsense of it not having to mean anything, because it does mean something to you. It always has.\n\nYou dress quickly and leave a note with the address to the Daylight Candle Shop. You strap the specter shield back onto your wrist. He might be pissed when he wakes up, but you will cross that bridge when you come to it.';
      },
      choices: [{ label: 'The Daylight Candle Shop', to: 'shop' }] },

    shop: { act: 1, ch: '4', pov: 'AUDRA', title: 'The Daylight Candle Shop', amb: ['candle', 'hum'],
      text: 'You drive back across town to the square and park in front of the Daylight Candle Shop. You open the door and are greeted by soft music and the scent of lavender. The shop is small but well lit. You walk through the narrow aisles, perusing the shelves, before the owner, Mackenzie Knox, steps from the back.\n\n@mackenzie “Oh... hello. I didn’t hear the door. I apologize. Were you looking for anything in particular?”\n\nHer rich dark skin has a glow, and if you believed in auras, you would associate that glow with the purity of the woman’s spirit. Instead, you wave those thoughts away.\n\n“Yes, I’m Special Agent Audra Wheeler of the FBI special unit charged with bringing criminal specters to justice. I’m investigating the death of Gwyneth Miller and need to ask you a few questions.”\n\nMackenzie’s body tenses. @mackenzie “You think a specter killed her?”\n\n“I do.”\n\n@mackenzie “Specters do not kill, Agent Wheeler. They may cause trouble, they may be mischievous, they may even be a little scary at times, but they do not kill. Specters are not like us. Once the body is dead the spirit is always at peace, one with the universe. A specter cannot kill any more than the wind or the rain.”\n\n“Have you ever heard of hurricanes?” you counter.\n\n@mackenzie “That is nature, not murder. But I can tell this has burdened you for a long time. Let me have your hands.”',
      choices: [
        { label: 'Give her your hands.', to: 'hands', fx: function (s) { s.f.hands = 1; } },
        { label: '“I just need to ask you a few questions about the day Gwyneth came into your shop.”', to: 'hands', fx: function (s) { s.f.hands = 0; s.trust.specters -= 1; } }
      ] },

    hands: { act: 1, ch: '4', pov: 'AUDRA', title: 'A Presence', amb: ['candle', 'hum'],
      text: function (s) {
        var t = s.f.hands
          ? '“Why?”\n\n@mackenzie “This case is personal to you.”\n\n“Why do you say that?” The hairs on the back of your neck rise.\n\n@mackenzie “I know things. Something about a sister,” she says, closing her eyes. “But it is not entirely clear.”\n\nYou figure it is worth a shot and give her your hands. Mackenzie turns your palms upward. You watch her face go through several emotional changes before she finally puts them back down.\n\n@mackenzie “It is not a specter. This presence is not a dead person’s spirit but an energy of someone living.”\n\n“Right, energy killed them.”\n\n@mackenzie “What I sense is that the energy is being used as a weapon.”\n\nShe opens a booklet to a beautifully colored chart of the human body and the chakras, then flips to a darker side of the same chart. @mackenzie “Everything can be corrupted. This is the crown chakra. It is what connects us to our spirituality. However, there are some who use it for external power and control, even telekinesis and mind control. And this is the throat chakra. It is linked to our ability to communicate, expressing our feelings, and telling the truth. I would guess that the killer is trying to silence them and keep something quiet or secret.”\n\n“If it is a person, how do I find out why?”\n\n@mackenzie “If you can figure out why, then you will know who.”'
          : '@mackenzie “Then I will say it plainly. It is not a specter. This presence is not a dead person’s spirit but an energy of someone living.”\n\n“Right, energy killed them.”\n\n@mackenzie “What I sense is that the energy is being used as a weapon.”\n\nHer tone is polite. Her warmth is gone.';
        return t + '\n\n“Before she died, Gwyneth purchased a candle from you, the Dry Spell Reliever.”\n\n@mackenzie “Would you like to try it?”\n\n“No, thank you. How does it work?”\n\n@mackenzie “The candle calls a romantic specter. When it is purchased the specter knows where to go and makes love to the person who lights it.”\n\n“Do you know this particular specter?”\n\n@mackenzie “I do. He’s my grandfather. He has nothing for you, but I know someone who does.”\n\nMackenzie looks around and then nods to an empty space. You watch as the air takes shape and an opaque specter manifests right in front of you. You reach for your specter shield and activate it.';
      },
      enter: function (s) { AS.clue(s, 'presence'); if (s.f.hands) AS.clue(s, 'throat'); },
      choices: [{ label: 'Look at who is coming forward', to: 'gwyn' }] },

    gwyn: { act: 1, ch: '4', pov: 'AUDRA', title: 'Hello, Gwyneth', amb: ['candle', 'cold'], sting: 'phase',
      enter: function (s) { if (s.shield) { s.f.dropped = 1; s.shield = false; AS.syncShield(); } else s.f.dropped = 0; AS.clue(s, 'abigail'); },
      text: function (s) {
        return (s.f.dropped ? 'Your shield flares, and the specter can come no closer. Her voice breaks into static until you switch it off.\n\n' : '') +
          'When you see that the specter coming forward is none other than Gwyneth Miller, you feel your entire body turn cold.\n\n@gwyn “Hello.”\n\nHer otherworldly voice is light, hollow, and seems somewhat amused.\n\n“Hello, Gwyneth. How long have you been here?”\n\n@gwyn “Since yesterday, I think. You want to solve my murder?”\n\n“Do you want me to solve your murder?”\n\n@gwyn “It won’t do me any good now, will it? But, I suppose you could save another young lady. I wasn’t going to speak to you at first, but then I heard you say that your sister was adopted. The Sheriff adopted me also. I didn’t find out until I graduated from college. That’s when I found out that my birth mother was murdered too. That case was never solved.”\n\nAn icy chill races up your spine. “When was this?”\n\n@gwyn “The day that I was born. She was strangled to death in the hospital. Very few people really knew what happened to her.”\n\n“What was her name?”\n\n@gwyn “Abigail Stevens.”\n\n“What can you tell me about your attack?”\n\n@gwyn “I was asleep. The most blissful sleep after the specter came and...” She giggles. @gwyn “Then I felt these fingers, but it wasn’t like fleshy fingers. They felt more like skeletal fingers, bones, and they burned. I remember gasping. The air was different. It was cooler than usual, but drier as well, and hard to breathe. I felt myself lose consciousness and then I was rising from my body. No one was there. I didn’t know where else to go, so I came here.”';
      },
      choices: [{ label: 'Go back to the B&B', to: 'file' }] },

    file: { act: 1, ch: '5', pov: 'AUDRA', title: 'Three Tarnished Pages', amb: ['hum'],
      text: 'You leave the candle shop and return to the B&B with a heavy feeling. You think about Gwyneth’s description of the air. You try to remember the air on the night of Kendra’s attack; it was cold and hard to breathe as well, but you attributed that all of these years to the mixture of adrenaline and panic.\n\nEthan is in the shower when you return. You sit on the bed and take several deep breaths.\n\n@ethan “What did you find out?”\n\n“Gwyn is now a specter. She says that she’s pretty sure it wasn’t a specter that killed her. Gwyn was adopted. Her birth mother was murdered in the hospital just after Gwyn was born, strangled to death. Her name was Abigail Stevens.”\n\nHe puts a secure hand on your back. As he rubs it in circular motions you allow yourself to feel the awful strangeness of the coincidence between your sister’s attack and the murder of Abigail Stevens. You are certain that whatever you uncover from here forward will only lead to truths that might be too ugly to leave you unchanged.\n\n@ethan “We should go back to the station and look up Abigail Stevens’ case. You don’t have to do this, Rook.”\n\n“Yes, I think I do,” you whisper.\n\nEthan walks to the ancient wall filing cabinet and unlocks the bottom drawer. @ethan “I don’t think this town has seen more than twenty murders in the last one hundred years.” He pulls out Abigail’s pitifully thin case file and flips through the three tarnished pages it contains.\n\nThe first thing to hit you is the image of Abigail on the medical examiner’s slab. Her throat is marked by a nasty red gash, with bruising around her mouth and jaw, her hands and arms, and around the wrists. “She was restrained and gagged,” you say out loud. By the label for the victim’s occupation is the word prostitute. If she had been a teacher, librarian, or even a waitress, you are sure more effort would have been made to bring her killer to justice.\n\nThen you look at the signature on the witness statements.\n\n“Jonathan Cordero, deputy sheriff. How did I miss that?”\n\n@ethan “The gory picture on the front cover probably had your attention.”\n\n“He didn’t tell me.”\n\n@ethan “Actually, AD Cordero suggested I come here. I thought about calling you a few times.”\n\n“Why didn’t you?”\n\n@ethan “The way we left things. I thought I was making things easier by volunteering to go quietly but you seemed angry about it. When I tried to talk to you, you blew me off. I don’t know why.”',
      enter: function (s) { AS.clue(s, 'cordero'); },
      choices: [
        { label: '“I had a miscarriage, Ethan.”', to: 'told', fx: function (s) { s.f.mc = 1; s.trust.ethan += 2; } },
        { label: '“It doesn’t matter now.”', to: 'told', fx: function (s) { s.f.mc = 0; s.trust.ethan -= 1; } }
      ] },

    told: { act: 1, ch: '5', pov: 'AUDRA', title: 'Losing You', amb: ['hum'],
      text: function (s) {
        return s.f.mc
          ? 'Ethan’s eyes widen in shock.\n\n@ethan “Why didn’t you tell me?”\n\n“Well, you were leaving. It didn’t seem to bother you to be moving a thousand miles away.”\n\n@ethan “I told you, I didn’t want your career to get shot up because of me.” Then he stands and quickly pulls you into a tight embrace. @ethan “Oh, Audra. You should have told me. You should have yelled and screamed at me. I should have known you better. Honestly, Rook, losing you was the worst thing to ever happen to me.”\n\nYou hug him back, loving the feel of his strong, secure arms around you.'
          : 'You shrug it off, and you can see that he does not believe you. @ethan “Okay. I’m sorry, Audra. I’m sorry I wasn’t there.”\n\nYou nod and turn back to the file. It is easier to look at the dead.';
      },
      choices: [{ label: 'A loud knock on the door', to: 'mayor' }] },

    mayor: { act: 1, ch: '5', pov: 'AUDRA', title: 'Not in My Town', amb: ['hum'], sting: 'knock',
      enter: function (s) { AS.clue(s, 'shelleys'); },
      text: 'The visitor doesn’t bother to wait on an answer. A short, stout man with dark skin, thinning hair, and thick glasses waddles through the door.\n\n@mayor “Cole! Is this that FBI lady?”\n\n“Agent Wheeler,” you supply, extending your hand.\n\n@mayor “Mayor Broner.” He ignores your hand and focuses his scowl on you. @mayor “It’s them specters, ain’t it? I won’t have this in my town! Cole, you were elected as sheriff to pick up where Miller left off, and now his own daughter is victim to them!”\n\n@ethan “We really don’t know that, sir.”\n\n@brendon “Yeah, calm down, Jimmy. Specters have been nothing but kind and generous to our town for the last ten years and you know it, Mr. Mayor.”\n\nThe sheriff’s station becomes incredibly crowded as another man, tall and good looking with dark bedroom eyes and salt and pepper hair, adds a fourth body to the small room.\n\n@mayor “I’m calling a special town hall meeting this Thursday to address the town concerns. I expect you and your lady friend here to have this mess straightened out by then.”\n\n@brendon “Brendon Shelley. It’s great to meet you, Agent Wheeler. I sit on the town council with our delightful mayor. Don’t mind him, he’s just old school. This ugly business is merely an isolated incident, right?”\n\nHis eyes roam to the case file in your hand and you watch as he becomes tense and straightens up.\n\n“We shall see,” you answer, and place the file out of sight.\n\nLater, in your room at the B&B, Ethan calls. There is something Councilman Shelley said that you can’t get out of your mind. His family. Who are they?\n\n@ethan “Oh, yeah. The Shelleys are the richest family in town. They managed to fund the new hospital about five years ago.”\n\n“New?” you wonder about the old hospital, where Abigail died. “What happened to the old hospital?”\n\n@ethan “I believe the old hospital is where they built the new park.”',
      choices: [{ label: 'Good night, Ethan', to: 'act1end' }] },

    act1end: { act: 1, endAct: true, ch: '5', pov: 'AUDRA', title: 'The Candle', amb: ['wind'], text: '' }
  };
})();
